### ISSUE TITLE
setFrequency should work on all frequencies

### ISSUE THREAD

**Issue by goatchurchprime** [MZachmann/LightLora_MicroPython#2]
In file sx127x.py you have a look up table instead of running the following calculation:

```Python
	def setFrequency(self, frequency):
		self._frequency = frequency
		k = ((frequency<<19)//32000000)
		self.writeRegister(REG_FRF_MSB, (k>>16)&0xff)
		self.writeRegister(REG_FRF_MID, (k>>8)&0xff)
		self.writeRegister(REG_FRF_LSB, k&0xff)
```

lifted from:
https://github.com/kersing/ESP-1ch-Gateway-v5.0/blob/master/ESP-sc-gway/_loraModem.ino#L314

**Comment by MZachmann** [comment]
I looked through the SX127x doc and agree that having a float frequency is more versatile and the math you're using agrees with the lookup table. I'll upgrade it.

**Comment by MZachmann** [comment]
This work has been completed and tested.
