### ISSUE TITLE
Doesn't work with Loboris MicroPython

### ISSUE THREAD

**Issue by torntrousers** [MZachmann/LightLora_MicroPython#5]
Thanks for the great library. There doesn't appear to be any other easy to use Lora library that works with MicroPython with a liberal license, so happy to find yours.

It doesn't work with the Loboris version of MicroPython though and that seems by far the best version for ESP32's - https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo

The only change needed is in sx127x _prepIrqHandler. Would you accept a pull request for this?

**Comment by MZachmann** [comment]
Sure, be my guest.
